package com.poc.lambda.pojo;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerated;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "StrudentTable")
public class StudentBean {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@DynamoDBAttribute(attributeName = "stdName")
	private String stdName;
	
	@DynamoDBAttribute(attributeName = "stdGrade")
	private String stdGrade;
	
	@DynamoDBAttribute(attributeName = "stdSubject")
	private String stdSubject;
	
	@DynamoDBAttribute(attributeName = "stdMark")
	private Integer stdMark;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getStdName() {
		return stdName;
	}
	public void setStdName(String stdName) {
		this.stdName = stdName;
	}
	public String getStdGrade() {
		return stdGrade;
	}
	public void setStdGrade(String stdGrade) {
		this.stdGrade = stdGrade;
	}
	public String getStdSubject() {
		return stdSubject;
	}
	public void setStdSubject(String stdSubject) {
		this.stdSubject = stdSubject;
	}
	public Integer getStdMark() {
		return stdMark;
	}
	public void setStdMark(Integer stdMark) {
		this.stdMark = stdMark;
	}
	
	
	@Override
	public String toString() {
	     String str = "Id:"+id+" Name:"+stdName+" Grade:"+stdGrade+" Subject:"+stdSubject+" Mark:"+stdMark;
		return str;
	}
}
